add ApartmentServletIntegrationTest
alexeyburak/andersenlab-hotel pull request #39
Opened 2023-10-30 09:21 UTC by aibarzhan

2023-10-30 09:48 UTC, AnnYaniv requested changes

2023-10-30 09:48 UTC, AnnYaniv commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +        File databaseFile = new File("C:\\Users\\Aibar\\Desktop\\andersenlab-hotel\\db.json");
Наш ci - такого не пропустит
пиши db.json что бы оно создавалось в корневом каталоге
и создай teardown метод что бы удалять файл в конце

2023-10-30 09:48 UTC, AnnYaniv commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +        HttpClient client = HttpClient.newHttpClient();
try(HttpClient client = HttpClient.newHttpClient()) {} и дальше так же

2023-10-30 10:40 UTC, alexeyburak requested changes

2023-10-30 10:40 UTC, alexeyburak commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +        id = UUID.randomUUID();
задай константное значение

2023-10-30 10:40 UTC, alexeyburak commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +
одна строка

2023-10-30 10:40 UTC, alexeyburak commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +
форматирование везде поправь

2023-10-30 10:40 UTC, alexeyburak commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +public class ApartmentServletIntegrationTest {
убрать public

2023-10-30 14:19 UTC, AnnYaniv requested changes
![image](https://github.com/alexeyburak/andersenlab-hotel/assets/67961111/467d0dd4-3304-4de2-afa1-44122f9b427a)

2023-10-31 05:29 UTC, aibarzhan commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +        File databaseFile = new File("C:\\Users\\Aibar\\Desktop\\andersenlab-hotel\\db.json");
DONE

2023-10-31 06:41 UTC, aibarzhan commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +        id = UUID.randomUUID();
Вот это  не понять. После обьявление константой нам нужно создать констуктор класса;
Создаю констуктор, тогда уже нельзя настраивать и обьявлять в @BeforeEach

2023-10-31 11:10 UTC, AnnYaniv requested changes

2023-10-31 11:10 UTC, AnnYaniv commented on domain/src/main/java/com/andersenlab/hotel/model/Apartment.java
> +
Слишком много пустых строк

2023-10-31 11:10 UTC, AnnYaniv commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> +        System.out.println(body);
System.out.println не используй
поменяй на логгер если так надо

2023-10-31 11:11 UTC, AnnYaniv commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +        id = UUID.randomUUID();
Uri - у тебя неизменно почему бы его не сделать final

2023-10-31 12:16 UTC, alexeyburak commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> +        System.out.println(body);
лучше ничего не писать

2023-10-31 13:47 UTC, alexeyburak requested changes

2023-10-31 13:47 UTC, alexeyburak commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> +        UUID apartmentId = UUID.fromString(body.get("id"));
а зачем поменял?

2023-10-31 13:47 UTC, alexeyburak commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +        String jsonBody;
очень много логических блоков, разделенных пустыми строками
1 блок) пишутся необходимые параметры
2) вызывается тестируемый метод
3) пишутся все ассерты

2023-10-31 13:47 UTC, alexeyburak commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +        String jsonBody;
и так везде

2023-10-31 13:47 UTC, alexeyburak commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +        id = UUID.randomUUID();
используй константное значение id
final UUID id = UUID.fromString("00000000-0000-0000-0000-000000000000");
тесты не должены зависеть от рандомного значения

2023-10-31 13:47 UTC, alexeyburak commented on domain/src/main/java/com/andersenlab/hotel/model/Apartment.java
> +    public Apartment(UUID id) {
а тут пустых строк не хватает

2023-10-31 13:47 UTC, alexeyburak commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +                    .uri(new URI("http://localhost:8080/apartments/adjust"))
это значение есть в константе

2023-10-31 13:47 UTC, alexeyburak commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +            throw new RuntimeException("Request was failed " + e);
не уверен по поводу обработки ошибок в тестах, я бы просто фэйлил тест и все

2023-10-31 15:13 UTC, aibarzhan commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> +        UUID apartmentId = UUID.fromString(body.get("id"));
![image](https://github.com/alexeyburak/andersenlab-hotel/assets/41124392/3d4d725a-93fc-4be2-99b8-c64214dee730)

Для POST запросов нужен был, чтобы JSON обьект сделать на основе сущности Apartment. А там обьявлен id просто

2023-10-31 15:28 UTC, aibarzhan commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +                    .uri(new URI("http://localhost:8080/apartments/adjust"))
Не понял что имеешь ввиду. Что имнно есть в константе?

2023-10-31 15:28 UTC, aibarzhan commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +        HttpClient client = HttpClient.newHttpClient();
DONE

2023-10-31 15:28 UTC, alexeyburak commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> +        UUID apartmentId = UUID.fromString(body.get("id"));
немного странно менять трестируемую логику, чтобы заработал тест, а не наоборот

2023-10-31 15:29 UTC, aibarzhan commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +        id = UUID.randomUUID();
> Uri - у тебя неизменно почему бы его не сделать final

DONE

2023-10-31 15:29 UTC, aibarzhan commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +
DONE

2023-10-31 15:30 UTC, aibarzhan commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +
DONE

2023-10-31 15:30 UTC, aibarzhan commented on domain/src/test/java/com/andersenlab/hotel/servlets/ApartmentServletIntegrationTest.java
> +public class ApartmentServletIntegrationTest {
DONE

2023-10-31 15:30 UTC, aibarzhan commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> +        System.out.println(body);
Это опечатка было. Забыл убрать. DONE

2023-10-31 15:31 UTC, alexeyburak commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +                    .uri(new URI("http://localhost:8080/apartments/adjust"))
ты сверху писать uri = "localhost:8080 и бальле"

2023-10-31 15:31 UTC, aibarzhan commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +        id = UUID.randomUUID();
> ния

DONE

2023-10-31 15:31 UTC, aibarzhan commented on domain/src/main/java/com/andersenlab/hotel/model/Apartment.java
> +    public Apartment(UUID id) {
> а тут пустых строк не хватает

DONE

2023-10-31 15:33 UTC, aibarzhan commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +            throw new RuntimeException("Request was failed " + e);
> не уверен по поводу обработки ошибок в тестах, я бы просто фэйлил тест и все

Когда с тестами не получалось, трудно было понять что именно. Поэтому для request и response отдельно try catch блок сделал чтобы в случае понять из-за чего

2023-10-31 16:05 UTC, aibarzhan commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +                    .uri(new URI("http://localhost:8080/apartments/adjust"))
> ты сверху писать uri = "localhost:8080 и бальле"

Да написал сверху

2023-10-31 17:08 UTC, AnnYaniv requested changes
@ SneakyThrows

2023-10-31 17:08 UTC, AnnYaniv commented on domain/src/main/java/com/andersenlab/hotel/model/Apartment.java
> +
У тебя 3(!!!) пустых строки - убери их пожалуйста

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> +        return new Response(body);
Зачем ты возращаешь то что тебе отправил юзер? Логичнее было бы оставить  new Response(HttpServletResponse.SC_ACCEPTED);

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +    ApartmentServletIntegrationTest() throws URISyntaxException {
Зачем тебе пустой конструктор да еще и для теста?

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +class ApartmentServletIntegrationTest {
между import и class - новая строка

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +            throw new RuntimeException("Request was failed " + e);
Используй анотацию @ SneakyThrows ты все равно все в рантайм обарачиваешь
и можешь избавиться от try catch конструкции

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +        } catch (IOException | InterruptedException e) {
@ SneakyThrows над методом и избався от try - catch

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +    void getApartmentById_shouldRespondStatusOk() {
@ SneakyThrows

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +    void getApartmentWithNonExistingId_shouldRespondEmptyApartment() {
@ SneakyThrows

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +        Assertions.assertThat(response.body()).isEqualTo("");
Проверяй на статус вместо (response.body()).isEqualTo("");

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +    void getListOfApartments_shouldReturnStatusCode200() {
@ SneakyThrows

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +    void deleteApartmentWithExistingId_shouldReturnStatusCode200() {
@ SneakyThrows

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +    void deleteApartmentNonWithExistingId_shouldReturnBadRequest() {
@ SneakyThrows

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +        String jsonBody;
@ SneakyThrows и все проблемы решены

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +    void addExistingApartment_shouldReturnBadRequest() {
@ SneakyThrows

2023-10-31 17:08 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +    void notAdjustApartmentPriceIfIdNotExist_shouldReturnBadRequest() {
@ SneakyThrows

2023-10-31 17:48 UTC, aibarzhan commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +    ApartmentServletIntegrationTest() throws URISyntaxException {
![image](https://github.com/alexeyburak/andersenlab-hotel/assets/41124392/93d6acc7-e24d-4edb-b21a-3a2f9b1ff374)
Ругает почему то

2023-10-31 17:49 UTC, aibarzhan commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> +        return new Response(body);
Опечатка и невнимательность. DONE

2023-10-31 17:55 UTC, aibarzhan commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +            throw new RuntimeException("Request was failed " + e);
> Используй анотацию @ SneakyThrows ты все равно все в рантайм обарачиваешь и можешь избавиться от try catch конструкции

Да до этого так и было с @SneakyThrows. Но препод сказал вроде не очень хорошое решение. Уж лучще try catch. Поэтому переделал

2023-10-31 18:03 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +    ApartmentServletIntegrationTest() throws URISyntaxException {
пиши через String значит

2023-11-01 08:49 UTC, AnnYaniv requested changes
Ну я хз что сказать. То что в один кеч обернул молодец.
А за то что ты третий раз раз не хочешь убирать пробелы c Apartment.java лови request changes.

2023-11-01 08:49 UTC, AnnYaniv commented on domain/src/main/java/com/andersenlab/hotel/model/Apartment.java
> +
Apartment.java-СТРОКИ.40-42.УБЕРИ.

2023-11-01 08:49 UTC, AnnYaniv commented on domain/src/main/java/com/andersenlab/hotel/model/Apartment.java
> +
Нет ну вообще это красиво - я третий раз прошу убрать 3 строки

2023-11-01 08:49 UTC, AnnYaniv commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> -
Зачем убрал пробел x1

2023-11-01 08:49 UTC, AnnYaniv commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> -
Зачем убрал пробел x2

2023-11-01 08:49 UTC, AnnYaniv commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> -
Зачем убрал пробел x3

2023-11-01 08:49 UTC, AnnYaniv commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> +        return new Response(body);
![image](https://github.com/alexeyburak/andersenlab-hotel/assets/67961111/19daa521-38a6-4fde-82e7-c72da4442336)
...

2023-11-01 08:49 UTC, AnnYaniv commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +        Assertions.assertThat(response.body()).isEqualTo("");
Проверяй на статус вместо (response.body()).isEqualTo(""); х2

2023-11-01 10:30 UTC, AnnYaniv approved these changes

2023-11-01 10:30 UTC, AnnYaniv commented on http-interface/src/main/java/com/andersenlab/hotel/http/AdjustServlet.java
> +        return new Response(body);
return new Response(HttpServletResponse.SC_ACCEPTED);

2023-11-01 10:38 UTC, Xini1 commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +        path = "test-db.json";
Обычно для тестов используют временные файлы и папки. У операционной системы есть место, куда можно складывать мусор, он переодически удаляется. https://www.baeldung.com/java-temp-directories https://www.baeldung.com/junit-5-temporary-directory

2023-11-01 10:38 UTC, Xini1 commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +            throw new RuntimeException(e.getMessage());
1) Не делайтеe.getMessage(), вы теряете стектрейс и понимание, где произошла изначальная ошибка
2) В тестах другие правила. void getApartmentByNonExistingId_shouldRespondBadRequest() throws Exception или throws ЧтоНибудь и сойдет

2023-11-01 10:38 UTC, Xini1 commented on http-interface/src/test/java/com/andersenlab/ApartmentServletIntegrationTest.java
> +                    .method("DELETE", HttpRequest.BodyPublishers.ofString("{\"id\":\"" + id + "\"}"))
Для json с кавычками неплохо текстовые блоки подходят

2023-11-01 10:45 UTC, alexeyburak approved these changes

2023-11-01 11:29 UTC, merged